name: structured_data_example
version: 0.1.0 # Semantic Versioning
description: Example for using structured data
homepage: https://github.com/Appsolutely-Wonderful/dart_structured_data
environment:
  sdk: '>=3.0.0'
dependencies:
  structured_data:
    path: '../'
  html: ^0.15.0
